parameters:
  - name: service_connection
    displayName: Environment Service Connection
    type: string
    default: sp-mac-dtos
  - name: environment
    displayName: Environment
    type: string
    default: dev
  - name: tf_version
    displayName: Environment
    type: string
    default: 1.5.7

trigger: none

variables:
  - group: dtos_dev_variables

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sp-mac-dtos'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'apt-get install terraform --version ${{ parameters.TF_VERSION }}'

#stages:
#  - stage: validate
#    jobs:
#    - job: validate
#      continueOnError: false
#      steps:
#        - task: TerraformTaskV4@4
#          continueOnError: false
#          displayName: TerraformInit
#          inputs:
#            provider: 'azurerm'
#            command: 'init'
#            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
#            backendAzureRmUseEnvironmentVariablesForAuthentication: false
#            backendServiceArm: 'sp-mac-dtos'
#            backendAzureRmResourceGroupName: 'rg-dtos-state'
#            backendAzureRmStorageAccountName: 'samacdtosdevstate'
#            backendAzureRmContainerName: 'tfstate'
#            backendAzureRmKey: 'dev.dtos.tfstate'
#
#        - task: TerraformTaskV4@4
#          continueOnError: false
#          displayName: TerraformPlan - ${{ parameters.environment }} Environment
#          inputs:
#            provider: 'azurerm'
#            command: 'plan'
#            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
#            commandOptions: '-var-file=environments/dtos_${{ parameters.environment }}.tfvars.config'
#            environmentServiceNameAzureRM: 'sp-mac-dtos'