parameters:
  - name: service_connection
    displayName: Environment Service Connection
    type: string
    default: sp-mac-dtos
  - name: tf_version
    displayName: TF Version
    type: string
    default: 1.5.7

trigger:
  paths:
    include:
    - infrastructure/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
