parameters:
  - name: service_connection
    displayName: Environment Service Connection
    type: string
    default: sp-mac-dtos
  - name: environment
    displayName: Environment
    type: string
    default: dev

trigger: none

variables:
  - group: dtos_dev_variables

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
    backendAzureRmUseEnvironmentVariablesForAuthentication: false
    backendServiceArm: 'sp-mac-dtos'
    backendAzureRmResourceGroupName: 'rg-dtos-state'
    backendAzureRmStorageAccountName: 'samacdtosdevstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.dtos.tfstate'
