# Things to change for further environments:
# - stage variable group name: dtos_ENVIRONMENT_variables
# - 

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/*  


variables:
  - group: dtos_global
  - name: TF_DIRECTORY
    value: '$(System.DefaultWorkingDirectory)/infrastructure'

pool:
  vmImage: ubuntu-latest

# Developlent environment

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    dependsOn: []

    variables:
      - group: dtos_development_variables

    jobs:

      - template: jobs/init_and_plan.yaml
        parameters:
          ENVIRONMENT: $(ENVIRONMENT)
          SERVICE_CONNECTION: $(SERVICE_CONNECTION) 
          TF_DIRECTORY: $(TF_DIRECTORY)
          TF_PLAN_ARTIFACT: $(TF_PLAN_ARTIFACT)

  - stage: terraform_apply
    displayName: Terraform Apply
    dependsOn: [terraform_plan]
    #condition: eq(dependencies.terraform_plan.outputs['init_and_plan.TerraformPlan.changesPresent'], 'true')
    condition: and(eq(dependencies.terraform_plan.outputs['init_and_plan.TerraformPlan.changesPresent'], 'true'), eq(variables['Build.Reason'], 'Manual'))
    variables:
      - group: dtos_development_variables

    jobs:
      - deployment: terraform_apply
        displayName: Terraform Apply - $(ENVIRONMENT)
        environment: $(ENVIRONMENT)
        strategy:
         runOnce:
           deploy:
            steps:
              - template: jobs/init_and_apply.yaml
                parameters:
                  ENVIRONMENT: $(ENVIRONMENT)
                  SERVICE_CONNECTION: $(SERVICE_CONNECTION)
                  TF_DIRECTORY: $(TF_DIRECTORY)
                  TF_PLAN_ARTIFACT: $(TF_PLAN_ARTIFACT)