parameters:
  - name: service_connection
    displayName: Environment Service Connection
    type: string
    default: fed-mac-dtos
  - name: environment
    displayName: Environment
    type: string
    default: dev
  - name: tf_version
    displayName: Environment
    type: string
    default: 1.5.7

trigger: none

variables:
  - group: dtos_dev_variables

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: '${{ parameters.TF_VERSION }}'

- task: Bash@3
  displayName: Echo Vars
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
    # script: 'make terraform-init dir="infrastructure"'
    script: |
      echo ls
      ls -l
      echo $(ARM_SUBSCRIPTION_ID)
      echo $(STATE_BLOB)

- task: AzureCLI@2
  displayName: Terraform Login
  inputs:
    azureSubscription: '${{ parameters.SERVICE_CONNECTION }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription $(ARM_SUBSCRIPTION_ID)
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
      echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
    addSpnToEnvironment: true
- task: Bash@3
  displayName: Terraform Init
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
    # script: 'make terraform-init dir="infrastructure"'
    script: |
      terraform init \
      -backend-config="resource_group_name=$(STATE_RG)" \
      -backend-config="storage_account_name=$(STATE_SA)" \
      -backend-config="container_name=$(STATE_CONT)" \
      -backend-config="key=$(STATE_BLOB)"


- task: Bash@3
  displayName: Terraform Plan
  inputs:
    targetType: 'inline'
    script: 'make terraform-plan dir="infrastructure" opts="-var-file=infrastructure/environments/${{ parameters.environment }}.tfvars.config"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

#stages:
#  - stage: validate
#    jobs:
#    - job: validate
#      continueOnError: false
#      steps:
#        - task: TerraformTaskV4@4
#          continueOnError: false
#          displayName: TerraformInit
#          inputs:
#            provider: 'azurerm'
#            command: 'init'
#            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
#            backendAzureRmUseEnvironmentVariablesForAuthentication: false
#            backendServiceArm: 'sp-mac-dtos'
#            backendAzureRmResourceGroupName: 'rg-dtos-state'
#            backendAzureRmStorageAccountName: 'samacdtosdevstate'
#            backendAzureRmContainerName: 'tfstate'
#            backendAzureRmKey: 'dev.dtos.tfstate'
#
#        - task: TerraformTaskV4@4
#          continueOnError: false
#          displayName: TerraformPlan - ${{ parameters.environment }} Environment
#          inputs:
#            provider: 'azurerm'
#            command: 'plan'
#            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
#            commandOptions: '-var-file=environments/dtos_${{ parameters.environment }}.tfvars.config'
#            environmentServiceNameAzureRM: 'sp-mac-dtos'