
trigger: none

variables:
  - group: dtos_global
  - name: TF_DIRECTORY
    value: '$(System.DefaultWorkingDirectory)/infrastructure'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: terraform_plan
    displayName: Terraform Plan - Development
    dependsOn: []

    variables:
      - group: dtos_$(ENVIRONMENT)_variables

    jobs:
      - template: jobs/init_and_plan.yaml
        parameters:
          ENVIRONMENT: $(ENVIRONMENT)
          SERVICE_CONNECTION: $(SERVICE_CONNECTION) 
          TF_DIRECTORY: $(TF_DIRECTORY)
          TF_PLAN_ARTIFACT: $(TF_PLAN_ARTIFACT)

  - stage: terraform_apply
    displayName: Terraform Apply - Development
    dependsOn: [terraform_plan]
    condition: eq(dependencies.terraform_plan.outputs['init_and_plan.TerraformPlan.changesPresent'], 'true')

    variables:
      - group: dtos_$(ENVIRONMENT)_variables

    jobs:
      - deployment: terraform_apply
        displayName: Terraform Apply - Development
        environment: $(ENVIRONMENT)
        strategy:
         runOnce:
           deploy:
            steps:
              - template: jobs/init_and_apply.yaml
                parameters:
                  ENVIRONMENT: $(ENVIRONMENT)
                  SERVICE_CONNECTION: $(SERVICE_CONNECTION)
                  TF_DIRECTORY: $(TF_DIRECTORY)
                  TF_PLAN_ARTIFACT: $(TF_PLAN_ARTIFACT)