parameters:
  - name: service_connection
    displayName: Environment Service Connection
    type: string
    default: sp-mac-dtos
  - name: environment
    displayName: Environment
    type: string
    default: dev
  - name: tf_version
    displayName: Environment
    type: string
    default: 1.5.7

trigger: none

variables:
  - group: dtos_dev_variables

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: '${{ parameters.TF_VERSION }}'

- task: AzureCLI@2
  displayName: Terraform Login
  inputs:
    azureSubscription: 'sp-mac-dtos'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version \
      az account show

- task: Bash@3
  displayName: Terraform Init
  inputs:
    targetType: 'inline'
    script: 'make terraform-init dir="infrastructure"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Bash@3
  displayName: Terraform Plan
  inputs:
    targetType: 'inline'
    script: 'make terraform-init dir="infrastructure"'
    workingDirectory: 'make terraform-plan dir="infrastructure" opts="-var-file=infrastructure/environments/dtos_${{ parameters.environment }}.tfvars.config"'

#stages:
#  - stage: validate
#    jobs:
#    - job: validate
#      continueOnError: false
#      steps:
#        - task: TerraformTaskV4@4
#          continueOnError: false
#          displayName: TerraformInit
#          inputs:
#            provider: 'azurerm'
#            command: 'init'
#            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
#            backendAzureRmUseEnvironmentVariablesForAuthentication: false
#            backendServiceArm: 'sp-mac-dtos'
#            backendAzureRmResourceGroupName: 'rg-dtos-state'
#            backendAzureRmStorageAccountName: 'samacdtosdevstate'
#            backendAzureRmContainerName: 'tfstate'
#            backendAzureRmKey: 'dev.dtos.tfstate'
#
#        - task: TerraformTaskV4@4
#          continueOnError: false
#          displayName: TerraformPlan - ${{ parameters.environment }} Environment
#          inputs:
#            provider: 'azurerm'
#            command: 'plan'
#            workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
#            commandOptions: '-var-file=environments/dtos_${{ parameters.environment }}.tfvars.config'
#            environmentServiceNameAzureRM: 'sp-mac-dtos'